### PR TITLE
Declare `lam` as an array

### LINKED ISSUE #44: syntax error in Allocatable Arrays section
Thanks for maintaining this extremely useful online resource.

One possible issue I have noticed: In the section **Allocatable Arrays**, an allocatable variable `lam` is used to illustrate how allocation can be done in a subroutine. Even though `lam` is treated as a one dimensional array, e.g. the statement `allocate(lam(5))`, the shape of the variable is never defined (i.e. `lam(:)` or using `dimension(:)`).

I am no expert and may be wrong, this may be intended just to show the general principle, but if the idea is to provide *minimum working example* code snippets, then perhaps this should be corrected?

### PR DESCRIPTION
**Pull request by certik**
Fixes #44.

### CODE REVIEW

**Comment by certik** [comment]
@jbdv-ife, please let me know if this fixes it.

**Comment by jbdv-ife** [comment]
looks good, however, it should similarly be applied in the next code section after "And use somewhere else:", i.e. `real(dp), allocatable :: lam(:)`

**Comment by certik** [comment]
@jbdv-ife good point, fixed in 638b9a5896fd3651154733f01e365f084271faec. Let me know if it looks good now.

**Comment by jbdv-ife** [comment]
Perfect, fixed :)

**Comment by certik** [comment]
Thanks for the review, it should appear online soon (once Travis finishes building it).

**Pull request merged**
